version: "3.8"

services:
  api:
    build: .
    container_name: bts-product-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
